<a href="https://colab.research.google.com/github/Pratham-gupta-235/PyTorch-Notes/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating Tensors

### Scaler Tensor

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # used to check the dimension of the tensor

0

In [6]:
# Vector : 1-D tensor
vector = torch.tensor([10,20,30])
vector

tensor([10, 20, 30])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [18]:
# Matrix : 2-D tensor
MATRIX = torch.tensor([[10,20,30],
                       [40,50,60]])
MATRIX

tensor([[10, 20, 30],
        [40, 50, 60]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 3])

In [21]:
MATRIX[1]

tensor([40, 50, 60])

In [32]:
# Tensor : n-D tensor
TENSOR = torch.tensor([[[10,20,30],
                        [40,50,60]],
                       [[70,80,90],
                        [100,110,120]],
                       [[130,140,150],
                        [160,170,180]]])
TENSOR

tensor([[[ 10,  20,  30],
         [ 40,  50,  60]],

        [[ 70,  80,  90],
         [100, 110, 120]],

        [[130, 140, 150],
         [160, 170, 180]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([3, 2, 3])

In [35]:
TENSOR[0]

tensor([[10, 20, 30],
        [40, 50, 60]])